version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  badge:
    lang: node10-express
    handler: ./badge
    image: badge:latest
    labels:
      com.openfaas.scale.zero: false
